using System.Collections;
using System.Collections.Generic;
using UnityEngine;
[System.Serializable]
public class Command
{
    public bool processed;
    public int type;//0: move 1:set hp and mp
    public bool sent = true;

    public int uuid;
}

//Schin 
//Documentation of child classes of Command

//Format:
//Classname [int value of type]
//Introductions
//Message direction, Client>Host or Host>Client or Bidirectional

//UnitMovedCmd [1]
//Generated by Simulator when Player moves a unit
//C>H

//UnitUpdateCmd [-1]
//Continuously updated by Simulator, contains a list of all current unit states.
//C>H H>C
